### ISSUE TITLE
End Game Cleanup and messaging

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#103]
Had our first group actually complete a full game through the bot!

Need some sort of cleanup phase, messaging to determine the winner, and maybe channel cleanup?

**Comment by patrickmilligan** [comment]
Would be really fun to have a "reveal reputation tiles and calculate" button, I'm not sure if those are just revealed by the player themselves right now?

Also, WOOHOOOOOOOOO

**Comment by Fingon00** [comment]
Have now added functionality that will total the points and declare the winner at the game end and in the chronicles
