### ISSUE TITLE
Movement - Incorrect Tiles Offered

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#106]
Player with transition drive is attempting to move 3 spaces from 204 to 102. Should be possible through 204 ->205 -> 103 -> 102.

However the bot is only offering movement options to 205, 306, and 407. There are a few 3 space tiles that should be available.

I did quickly check to make sure the transition drive movement stat was correct and it seems to be.

![image](https://github.com/user-attachments/assets/15a695e2-bb37-4804-a315-69a16da136fb)

[aeb70 (1).json](https://github.com/user-attachments/files/17131877/aeb70.1.json)

**Comment by Fingon00** [comment]
Fixed
