### ISSUE TITLE
Parts descriptions

### ISSUE THREAD

**Issue by patrickmilligan** [AsyncEclipse/DiscordBot#124]
In the same vein that Techs needed a set of descriptions, Ship Parts could also benefit from descriptions.

The standard ship parts are easy to understand, but some things like Morph Shield and Jump Drive would benefit from clarification.

All parts now have a "description":"", line with relevant text copied verbatim from the tech.json, the player trifold guide from Lautapelit, with some clarifications that I recommend.

Bird, if you write a search command for techs, can you also write one for searching ship parts for their description?

**Comment by TaylorBoyd** [comment]
will do

**Comment by TaylorBoyd** [comment]
Done
