### ISSUE TITLE
Faction JSON File

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#2]
Faction JSON file needs to be filled out with all the factions in the same style as Hydran. Should be a dictionary of dictionaries with the main key the shortened 3 letter version of the faction.

**Comment by patrickmilligan** [comment]
Uploading this shortly

**Comment by patrickmilligan** [comment]
faction.json now includes information for all alien species + 6 unique humans as "ter1" through "ter6". The only difference between the humans is their home system, which is purely aesthetic. But differentiating them now might be helpful in the future for plotting the map.

They recently released 4 new factions with Outcasts and Seekers. If I can get scans of their faction boards then I'll update this, the new TTS mod should have them soon.

Resolving this for now.
