### ISSUE TITLE
Supernova tiles flip on explode

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#278]
Missed this myself when reading the rules. Supernova's are supposed to flip over to the blank sector 3 side when they explode.

![image](https://github.com/user-attachments/assets/44213768-d63b-4b22-b137-5a9c9279cd90)

**Comment by Fingon00** [comment]
I think we need a special tile to represent this, some sort of unique image, to show its not explorable. As it works rn it should be an edge case where someone wants to traverse across it

**Comment by Fingon00** [comment]
I think I already have something about not influencing black holes, so Ill see what I can do
