### ISSUE TITLE
Move Actions and Traitor

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#279]
If you have traded ambassadors with someone, moving through their territory should not automatically trigger traitor status. Only if you end your full turn (move action) in their territory or a ship is pinned and left stuck in place.

Currently if a player has 2+ move activations to use during a move action, and only stops in the other players territory, they are immediately given traitor status which is should not happen.

I just learned this myself today.

**Comment by Fingon00** [comment]
Fixed
