### ISSUE TITLE
Tile JSON File

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#3]
Tile JSON file needs to be filled out. Should be a dictionary of dictionaries with the main key as the sector ID .

**Comment by patrickmilligan** [comment]
After running through these, it's pretty clear that I can't define planet placement as types of arrangements. Everything is pretty unique based on where the artist placed the planet.

Fortunately, I can just open the file in inkscape and quickly plot x y coordinates for each population cube space. I've gotta put a pin in this for now but I'll just chip away at a "hexes.json" file. Got something like 70-80 tiles to do so it's gonna be a little slow
