### ISSUE TITLE
Reputation Tiles

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#32]
- Add reputation tile "deck" to gamestate
- Adjust setup_complete to start Eridani with 2

**Comment by patrickmilligan** [comment]
Do we just need a dictionary with point values and abundances for 1-4 point tiles?

**Comment by TaylorBoyd** [comment]
@patrickmilligan I think if all reputation tiles are just VP numbers, we can store those as a single list in the gamestate. No need for a JSON file
