### ISSUE TITLE
/tile manage_population does not work correctly

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#62]
Currently this command just adds numbers to 0 index of the population list.

For example...2 open slots in a sector tile [0, 0]. Adding 2 to this tile should set the tile to [1, 1] but instead sets to [2, 0].

Optionally we could add some protections to prevent impossible cube placements.

**Comment by Fingon00** [comment]
Believe this is partially intentional, I built things to look at the 0th position. I can adjust logic to prevent impossible cube placements, but this behavior could remain without issue

**Comment by Fingon00** [comment]
The storage is a useful in built max cube value, I think we can leave it as is

**Comment by Fingon00** [comment]
Ya, it's a little strange but at the same time should work well

**Comment by Fingon00** [comment]
I've added some protection
