### ISSUE TITLE
Start game message needs to be "awaited"

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#66]
/home/eatingflowers/DiscordBot/./commands/setup_commands.py:165: RuntimeWarning: coroutine 'Messageable.send' was never awaited
  actions.send("Draft factions and turn position in the manner of your choice, then setup the game with /setup game. Enter the players in the order they should take turns in (i.e. enter first player first)")

**Comment by Fingon00** [comment]
Added
