### ISSUE TITLE
Remove influence command - Does not remove from Map

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#69]
Players using this command mentioned it will move the discs accurately on the player sheet, but did not remove from the map.

**Comment by Fingon00** [comment]
Not sure the influence disk is a problem, but fixed the resource cube problem

**Comment by Fingon00** [comment]
@TaylorBoyd honestly not entirely sure still, but added some additional checks which should catch and prevent it. Works on my local at least

**Comment by Fingon00** [comment]
Fixing the cache issue
