### ISSUE TITLE
Upgrade Failing

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#74]
Player attempting second upgrade on the same ship. Cruiser in this case

![image](https://github.com/user-attachments/assets/4a840f8c-6f6c-4f66-b4f7-0587876f8350)

![image](https://github.com/user-attachments/assets/f7cfd46b-b6cb-4806-ac96-aea24e9d5b55)

**Comment by Fingon00** [comment]
Fixed, was an error with how I tried to implement discovery tile upgrades, I forgot to modify the second upgrade to accomodate
