### ISSUE TITLE
Population Cubes Placement

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#82]
Player placed two money cubes at once but this process followed the "old" method and filled the list like [1, 1] instead of our new method of [2, 0].

The cube was placed and the income was correctly adjusted but the map will not draw the second cube.

"106": {"owner": "red", "name": "Pollux", "ring": 1, "disctile": 0, "player_ships": [], "money_pop": [], "money1_snap": [], "money2_snap": [], "moneyadv_pop": [], "moneyadv1_snap": [], "moneyadv2_snap": [], "scienceadv_pop": [], "science1adv1_snap": [], "science2adv2_snap": [], "science_pop": [1, 1], "science1_snap": [445, 673], "science2_snap": [308, 673], "material_pop": [], "material1_snap": [], "material2_snap": [], "materialadv_pop": [], "materialadv1_snap": [], "materialadv2_snap": [], "neutral_pop": [], "neutral1_snap": [], "neutral2_snap": [], "neutral_adv_pop": [], "neutraladv1_snap": [], "neutraladv2_snap": [], "int_snap": [338, 200], "cru_snap": [668, 226], "drd_snap": [665, 650], "sb_snap": [201, 436], "mon_snap": [513, 450], "orb_snap": [404, 317], "ai_snap": [513, 450], "wormholes": [0, 2, 3, 5], "vp": 2, "artifact": 0, "ancient": 0, "guardian": 0, "gcds": 0, "warp": 0, "type": "standard", "sector": "102", "orientation": 240}

**Comment by Fingon00** [comment]
I've added a couple lines to draw the cube if something is in the second slot. When I'm less tired, I'll check why it got put in the second slot and see if I can fix that
