### ISSUE TITLE
Advanced Cube on Advanced Neutral

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#83]
Possible issue, player not allowed to place an advanced science cube on the advanced neutral square. They do have advanced science researched and one colony ship left.

**Comment by Fingon00** [comment]
Havent figured out this one yet tbh

**Comment by TaylorBoyd** [comment]
May have been related to the key error "neutraladv_pop" vs "neutral_adv_pop" I fixed in the other issue.

**Comment by TaylorBoyd** [comment]
Maybe we should fix it in the sectors instead of trying to force the code to work differently. Seems to be the issue here for sure.

**Comment by TaylorBoyd** [comment]
Fixed sectors.json to correct the naming convention. Will not help currently running games but new ones should work now.
