### ISSUE TITLE
Player Cannot Pass After Research

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#84]
Player was researching their second tech of artifact key and caused this error:

![image](https://github.com/user-attachments/assets/6bedbfd7-116f-44ea-b3f6-9908cd153d75)

Player not able to pass after.

**Comment by Fingon00** [comment]
Im not sure why that line even exists. Doesnt make sense why Id check the trade value there, just a brain fart.  Deleted that check
