### ISSUE TITLE
Manage Population - New Key Error

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#98]
Looks to happen upon subtracting a cube from the player pool

![image](https://github.com/user-attachments/assets/97229625-538a-4b98-80d6-08ae9d04da76)

**Comment by TaylorBoyd** [comment]
I don't think this commands works with neutral spaces because you need to pick which track to pull from, there is no neutral track.

**Comment by Fingon00** [comment]
Believe we've addressed this
